# Generated by Django 4.2 on 2025-07-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent_id',
            new_name='payment_intent_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mock', 'Mock Payment')], max_length=50),
        ),
    ]
